name: Release

on:
  workflow_run:
    workflows:
      - "Test"
    branches:
      - master
    types:
      - completed


jobs:
  pre_ci:
    name: Prepare CI environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          # We need to fetch with a depth of 2 for pull_request so we can do HEAD^2
          fetch-depth: 2

        # If this workflow was triggered by a push then resolve the commit message from HEAD
        # It is stored in output steps, to be referenced with ${{ steps.push_get_commit_message.outputs.push_commit_message }}
      - name: "Get commit message"
        id: push_get_commit_message
        run:
          echo ::set-output name=push_commit_message::$(git log --format=%B -n 1 HEAD)

    # Finally we want to make the commit message available to other jobs. This can be done with job-level outputs
    # However as we do not know whether the commit message was set in Push or Pull Request event we need to do some
    # bash magic to resolve the one or the other
    #
    # For **Pull Request** events this will resolve to something like "$( [ -z "commit message pr" ] && echo "" || echo "commit message pr" )" which then resolves to just "commit message pr"
    #
    # For **Push** events this will resolve to something like "$( [ -z "" ] && echo "commit message push"  || echo "" )" which then resolves to just "commit message push"
    outputs:
      commit_message: $( echo "${{ steps.push_get_commit_message.outputs.push_commit_message }}" )
  bump_version:
    runs-on: ubuntu-latest
    needs:
      - pre_ci
    if: ${{ contains(needs.pre_ci.outputs.commit_message), '[ci release]') && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Git Fetch Unshallow
        run: git fetch --prune --unshallow

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.35.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true

      - name: Refresh pkg.go.dev
        uses: andrewslotin/go-proxy-pull-action@master